name: ESMV_STORE
description: A new Flutter project.
version: 1.0.0

environment:
  sdk:  '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^7.0.7
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  country_code_picker: ^3.0.0
  percent_indicator: ^4.2.3
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.6
  firebase_core: ^2.32.0
  dio: ^5.4.3+1
  provider: ^6.1.2
  flutter_localization: ^0.2.0
  infinite_scroll_pagination: ^4.0.0

dependency_overrides:
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/

